http://127.0.0.1:8000
Content-Type: application/json
POST /login
{
    "email": "anhviet5121pc@gmail.com",
    "password": "123456789"
}

// test
http://127.0.0.1:8000
Cookie: token=eyJhbGciOiJIUzI1NiJ9.ImFuaHZpZXQ1MTIxcGNAZ21haWwuY29tIg.zZlRh8o6ovy1PsrWEnOIxlUK56FX9sotKYQQo2NtyEc
GET /test
